### ISSUE TITLE
error: no viable conversion from 'std::istream' (aka 'basic_istream<char>') to 'void *'

### ISSUE THREAD

**Issue by sjackman** [bcgsc/abyss#35]
Does not compile on OS X 10.9 Mavericks

```
clang++ -DHAVE_CONFIG_H -I. -I../../Assembly -I..  -I../.. -I../../Common -I../../DataLayer -I..     -Wall -Wextra -Werror -g -O2 -MT libassembly_a-AssemblyAlgorithms.o -MD -MP -MF .deps/libassembly_a-AssemblyAlgorithms.Tpo -c -o libassembly_a-AssemblyAlgorithms.o `test -f 'AssemblyAlgorithms.cpp' || echo '../../Assembly/'`AssemblyAlgorithms.cpp
In file included from ../../Assembly/AssemblyAlgorithms.cpp:4:
../../DataLayer/FastaReader.h:49:35: error: no viable conversion from
      'std::istream' (aka 'basic_istream<char>') to 'void *'
                operator void*() const { return m_in; }
                                                ^~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/ios:576:9: note: 
      candidate function
        operator bool() const {return !fail();}
        ^
1 error generated.
```
