### ISSUE TITLE
Fails to compile on OS X 10.8 Mountain Lion

### ISSUE THREAD

**Issue by sjackman** [bcgsc/abyss#13]
ABySS 1.3.4 fails to compile on OS X 10.8 Mountain Lion. There's some issue with stl_relops.h.

```
/usr/bin/clang++ -DHAVE_CONFIG_H -I. -I..  -I.. -I../Common -I.   -isystem /usr/local/include -Wall -Wextra -Werror -Os -w -pipe -march=native -Qunused-arguments -mmacosx-version-min=10.8 -c -o abyss_drawgraph-drawgraph.o `test -f 'drawgraph.cc' || echo './'`drawgraph.cc
In file included from junction.cc:5:
../Graph/ContigGraphAlgorithms.h:332:19: error: call to function 'operator!=' that is neither visible in the template definition nor found by argument-dependent lookup
                } else if (g[e] != g[f]) {
                                ^
junction.cc:192:21: note: in instantiation of function template specialization 'addComplementaryEdges<DirectedGraph<NoProperty, NoProperty> >' requested here
                size_t numAdded = addComplementaryEdges(scaffoldG);
                                  ^
/usr/include/c++/4.2.1/bits/stl_relops.h:92:7: note: 'operator!=' should be declared prior to the call site or in the global namespace
      operator!=(const _Tp& __x, const _Tp& __y)
      ^
1 error generated.
make[1]: *** [abyss_junction-junction.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from scaffold.cc:9:
In file included from ../Graph/Assemble.h:6:
In file included from ../Graph/DepthFirstSearch.h:4:
../Graph/ContigGraphAlgorithms.h:332:19: error: call to function 'operator!=' that is neither visible in the template definition nor found by argument-dependent lookup
                } else if (g[e] != g[f]) {
                                ^
scaffold.cc:702:20: note: in instantiation of function template specialization 'addComplementaryEdges<DirectedGraph<Length, DistanceEst> >' requested here
        size_t numAdded = addComplementaryEdges(g);
                          ^
/usr/include/c++/4.2.1/bits/stl_relops.h:92:7: note: 'operator!=' should be declared prior to the call site or in the global namespace
      operator!=(const _Tp& __x, const _Tp& __y)
      ^
1 error generated.
make[1]: *** [abyss_scaffold-scaffold.o] Error 1
In file included from drawgraph.cc:13:
../Graph/ContigGraphAlgorithms.h:332:19: error: call to function 'operator!=' that is neither visible in the template definition nor found by argument-dependent lookup
                } else if (g[e] != g[f]) {
                                ^
drawgraph.cc:177:2: note: in instantiation of function template specialization 'addComplementaryEdges<DirectedGraph<Length, DistanceEst> >' requested here
        addComplementaryEdges(g);
        ^
/usr/include/c++/4.2.1/bits/stl_relops.h:92:7: note: 'operator!=' should be declared prior to the call site or in the global namespace
      operator!=(const _Tp& __x, const _Tp& __y)
      ^
1 error generated.
make[1]: *** [abyss_drawgraph-drawgraph.o] Error 1
make: *** [install-recursive] Error 1
Error: #<BuildError: Failed executing: make install >
```
