### ISSUE TITLE
Does not compile with GCC 4.7

### ISSUE THREAD

**Issue by sjackman** [bcgsc/abyss#7]
../../FMIndex/FMIndex.h: In function 'std::istream& operator>>(std::istream&, FMIndex&)':
../../FMIndex/FMIndex.h:540:7: error: variable 'c' set but not used [-Werror=unused-but-set-variable]

and

I am trying to compile Abyss 1.3.3 on a Linux machine with GCC 4.7.0
and Boost 1.49.0 and am running into the following issues:

abyss-fixmate.cc:130:8: error: ‘intptr_t’ does not name a type
abyss-fixmate.cc: In function ‘void printProgress(const Alignments&)’:
abyss-fixmate.cc:143:38: error: expected type-specifier before
‘intptr_t’
abyss-fixmate.cc:143:38: error: expected ‘>’ before ‘intptr_t’
abyss-fixmate.cc:143:38: error: expected ‘(’ before ‘intptr_t’
abyss-fixmate.cc:143:38: error: ‘intptr_t’ was not declared in this
scope
abyss-fixmate.cc:143:54: error: ‘sbrk’ was not declared in this scope
abyss-fixmate.cc:143:59: error: ‘sbrk0’ was not declared in this scope
abyss-fixmate.cc:143:64: error: expected ‘)’ before ‘;’ token
make[2]: **\* [abyss_fixmate-abyss-fixmate.o] Error 1
make[2]: Leaving directory `/n/home01/jhess/Software/abyss-1.3.3_n/
abyss-1.3.3/ParseAligns'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/n/home01/jhess/Software/abyss-1.3.3_n/
abyss-1.3.3'
make: **\* [all] Error 2

I managed to alleviate some of those by including <cstdint> in abyss-
fixmate.cc and -std=gnu++11 in the compilation command but I am still
seeing the following errors which I am at loss about:

abyss-fixmate.cc:130:58: error: ‘sbrk’ was not declared in this scope
abyss-fixmate.cc: In function ‘void printProgress(const Alignments&)’:
abyss-fixmate.cc:143:54: error: ‘sbrk’ was not declared in this scope
