### ISSUE TITLE
error: unused typedef 'boost_concept_check30'

### ISSUE THREAD

**Issue by sjackman** [bcgsc/abyss#165]
Fails to build on TravisCI macOS with boost 1.56.0
```
clang++ -DHAVE_CONFIG_H -I. -I..  -I.. -I../Common -I../DataLayer -I/home/travis/build/bcgsc/abyss  -isystem/usr/lib/openmpi/include    -isystem/home/travis/build/bcgsc/abyss/boost_1_56_0 -Wall -Wextra -Werror -fopenmp -g -O2 -MT konnector-konnector.o -MD -MP -MF .deps/konnector-konnector.Tpo -c -o konnector-konnector.o `test -f 'konnector.cc' || echo './'`konnector.cc
In file included from konnector.cc:8:
In file included from ./konnector.h:8:
In file included from ../Graph/ConstrainedBidiBFSVisitor.h:10:
../Graph/AllPathsSearch.h:30:5: error: unused typedef 'boost_concept_check30'
      [-Werror,-Wunused-local-typedef]
    BOOST_CONCEPT_ASSERT((boost::IncidenceGraphConcept<IncidenceGraph>));
```
https://travis-ci.org/bcgsc/abyss/jobs/279391532#L972
